apiVersion: v1
kind: Service
metadata:
  name: goapp-service
spec:
  type: LoadBalancer # Use ClusterIP for internal services
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: goapp
